package pharmaceuticals.nl.peptrix.gui.creatematrix.center;

import java.awt.Checkbox;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.TextField;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

import pharmaceuticals.nl.peptrix.Controller;

public class PanelPeakFind {

	JPanel peakfindinputpanel;

	Controller cc;

	public PanelPeakFind(Controller cc) {
		peakfindinputpanel = new JPanel();
		this.cc = cc;
	}

	public JPanel getpanel() {
		return peakfindinputpanel;
	}

	public void fill_panels_with_fields() {
		peakfindinputpanel.removeAll();
		cc.btngroup = new ButtonGroup();
		peakfindinputpanel.setBorder(BorderFactory.createTitledBorder("Peak finding"));
		GridBagLayout gridbagpeakfind = new GridBagLayout();
		peakfindinputpanel.setLayout(gridbagpeakfind);
		GridBagConstraints constraintspeakfind = new GridBagConstraints();
		constraintspeakfind.anchor = GridBagConstraints.FIRST_LINE_START;
		constraintspeakfind.insets = new Insets(2, 2, 2, 2);
		cc.labeldeltamzsearch = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 1;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.labeldeltamzsearch, constraintspeakfind);
		peakfindinputpanel.add(cc.labeldeltamzsearch);
		cc.inputdeltamzsearch = new TextField(4);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 1;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.inputdeltamzsearch, constraintspeakfind);
		peakfindinputpanel.add(cc.inputdeltamzsearch);
		cc.ppm = new JRadioButton("ppm");
		cc.ppm.setMnemonic(KeyEvent.VK_0);
		cc.btngroup.add(cc.ppm);
		cc.ppm.addActionListener(cc);
		constraintspeakfind.gridx = 3;
		constraintspeakfind.gridy = 1;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.ppm, constraintspeakfind);
		peakfindinputpanel.add(cc.ppm);
		cc.labelquantilepeakfinding = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 2;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.labelquantilepeakfinding, constraintspeakfind);
		peakfindinputpanel.add(cc.labelquantilepeakfinding);
		cc.inputquantilepeakfinding = new TextField(4);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 2;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.inputquantilepeakfinding, constraintspeakfind);
		peakfindinputpanel.add(cc.inputquantilepeakfinding);
		cc.Da = new JRadioButton("Da");
		cc.Da.setMnemonic(KeyEvent.VK_1);
		cc.btngroup.add(cc.Da);
		cc.Da.addActionListener(cc);
		constraintspeakfind.gridx = 3;
		constraintspeakfind.gridy = 2;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.Da, constraintspeakfind);
		peakfindinputpanel.add(cc.Da);
		cc.labeldeltamzcombine = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 3;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.labeldeltamzcombine, constraintspeakfind);
		peakfindinputpanel.add(cc.labeldeltamzcombine);
		cc.inputdeltamzcombine = new TextField(4);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 3;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.inputdeltamzcombine, constraintspeakfind);
		peakfindinputpanel.add(cc.inputdeltamzcombine);
		cc.labelnoisyspectra = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 4;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.labelnoisyspectra, constraintspeakfind);
		peakfindinputpanel.add(cc.labelnoisyspectra);
		cc.peaksnoisyspectra = new TextField(6);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 4;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.peaksnoisyspectra, constraintspeakfind);
		peakfindinputpanel.add(cc.peaksnoisyspectra);
		cc.labelnumberofreplicatessample = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 5;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.labelnumberofreplicatessample, constraintspeakfind);
		peakfindinputpanel.add(cc.labelnumberofreplicatessample);
		cc.inputnumberofreplicatessample = new TextField(6);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 5;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.inputnumberofreplicatessample, constraintspeakfind);
		peakfindinputpanel.add(cc.inputnumberofreplicatessample);
		cc.labelthresholdbinarytable = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 6;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.labelthresholdbinarytable, constraintspeakfind);
		peakfindinputpanel.add(cc.labelthresholdbinarytable);
		cc.inputthresholdbinarytable = new TextField(6);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 6;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.inputthresholdbinarytable, constraintspeakfind);
		peakfindinputpanel.add(cc.inputthresholdbinarytable);
		cc.labelminimummass = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 7;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.labelminimummass, constraintspeakfind);
		peakfindinputpanel.add(cc.labelminimummass);
		cc.inputminimummass = new TextField(6);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 7;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.inputminimummass, constraintspeakfind);
		peakfindinputpanel.add(cc.inputminimummass);
		cc.labelmaximummass = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 8;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.labelmaximummass, constraintspeakfind);
		peakfindinputpanel.add(cc.labelmaximummass);
		cc.inputmaximummass = new TextField(6);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 8;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.inputmaximummass, constraintspeakfind);
		peakfindinputpanel.add(cc.inputmaximummass);
		cc.minimumcountmasses = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 9;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.minimumcountmasses, constraintspeakfind);
		peakfindinputpanel.add(cc.minimumcountmasses);
		cc.inputminimumcountmasses = new TextField(6);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 9;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.inputminimumcountmasses, constraintspeakfind);
		peakfindinputpanel.add(cc.inputminimumcountmasses);
		cc.labeltimewindow_lc_ms = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 10;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.labeltimewindow_lc_ms, constraintspeakfind);
		peakfindinputpanel.add(cc.labeltimewindow_lc_ms);
		cc.input_time_widow_lc_ms = new TextField(12);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 10;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.input_time_widow_lc_ms, constraintspeakfind);
		peakfindinputpanel.add(cc.input_time_widow_lc_ms);
		cc.labeltimealignment = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 11;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.labeltimealignment, constraintspeakfind);
		peakfindinputpanel.add(cc.labeltimealignment);
		cc.checkboxtimealignment = new Checkbox();
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 11;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.checkboxtimealignment, constraintspeakfind);
		peakfindinputpanel.add(cc.checkboxtimealignment);
		cc.labelpointstimealignment = new JLabel();
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 12;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.labelpointstimealignment, constraintspeakfind);
		peakfindinputpanel.add(cc.labelpointstimealignment);
		cc.inputpointstimealignment = new TextField(12);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 12;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.inputpointstimealignment, constraintspeakfind);
		peakfindinputpanel.add(cc.inputpointstimealignment);
		JLabel labelchangeingradient1 = new JLabel("change in gradient after time (min)");
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 13;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(labelchangeingradient1, constraintspeakfind);
		peakfindinputpanel.add(labelchangeingradient1);
		cc.input_changeingradient1 = new TextField(12);
		cc.input_changeingradient1.addFocusListener(cc);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 13;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.input_changeingradient1, constraintspeakfind);
		peakfindinputpanel.add(cc.input_changeingradient1);
		JLabel labelchangeingradient2 = new JLabel("change in gradient after time (min)");
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 14;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(labelchangeingradient2, constraintspeakfind);
		peakfindinputpanel.add(labelchangeingradient2);
		cc.input_changeingradient2 = new TextField(12);
		cc.input_changeingradient2.addFocusListener(cc);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 14;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.input_changeingradient2, constraintspeakfind);
		peakfindinputpanel.add(cc.input_changeingradient2);
		JLabel labelchangeingradient3 = new JLabel("change in gradient after time (min)");
		constraintspeakfind.gridx = 1;
		constraintspeakfind.gridy = 15;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(labelchangeingradient3, constraintspeakfind);
		peakfindinputpanel.add(labelchangeingradient3);
		cc.input_changeingradient3 = new TextField(12);
		cc.input_changeingradient3.addFocusListener(cc);
		constraintspeakfind.gridx = 2;
		constraintspeakfind.gridy = 15;
		constraintspeakfind.gridwidth = 1;
		constraintspeakfind.gridheight = 1;
		gridbagpeakfind.setConstraints(cc.input_changeingradient3, constraintspeakfind);
		peakfindinputpanel.add(cc.input_changeingradient3);

	}
}
